import { createAction } from "@reduxjs/toolkit";

export const setPage = createAction("@ui/setPage")
export const logIn = createAction("@ui/logIn")
export const logOut = createAction("@ui/logOut")
export const addCard = createAction("@ui/AddCard")
export const authenticate = createAction("@ui/Auth")
export const reg = createAction("@ui/Reg")
export const regCard = createAction("@ui/RegCard")
export const authToken = createAction("@ui/AuthToken")
export const setCurrentCardName = createAction("@ui/CurrentCardName")
export const setCurrentCardDate = createAction("@ui/CurrentCardDate")
export const setCurrentCardNumber = createAction("@ui/CurrentCardNumber")
export const setCurrentCardCvc = createAction("@ui/CurrentCardCvc")
export const setCardNumberCounter = createAction("@ui/cardNumberCounter")
export const setCardDateCounter = createAction("@ui/cardDateCounter")