import { createAction } from "@reduxjs/toolkit";

export const setPage = createAction("@ui/setPage")
export const logIn = createAction("@ui/logIn")
export const logOut = createAction("@ui/logOut")
export const addCard = createAction("@ui/addCard")
export const authenticate = createAction("@ui/auth")
export const reg = createAction("@ui/reg")
export const regCard = createAction("@ui/regCard")
export const authToken = createAction("@ui/authToken")
export const setCardName = createAction("@ui/cardName")
export const setCardDate = createAction("@ui/cardDate")
export const setCardNumber = createAction("@ui/cardNumber")
export const setCardCvc = createAction("@ui/cardCvc")
export const setAddresses = createAction("@ui/setAddresses")
export const setFirstAddress = createAction("@ui/setFirstAddress")
export const setSecondAddress = createAction("@ui/setSecondAddress")
export const setFirstArrayAddress = createAction("@ui/setArrayFirstAddress")
export const setSecondArrayAddress = createAction("@ui/setArraySecondAddress")
export const orderReq = createAction("@ui/orderReq")
export const coords = createAction("@ui/coords")
export const needTaxi = createAction("@ui/needTaxi")
export const taxiReady = createAction("@ui/taxiReady")
export const checkCard = createAction("@ui/checkCard")
export const checkCardFromProfile = createAction("@ui/checkCardFromProfile")
export const isCardChanged = createAction("@ui/isCardChanged")
export const carChange = createAction("@ui/carChange")