import { createSelector } from '@reduxjs/toolkit'

const selectUI = (store) => store.ui;
export const selectPage = createSelector(selectUI, (ui) => ui.page)
export const logged = createSelector(selectUI , (ui) => ui.isLoggedIn)
export const tokenSelector = createSelector(selectUI, (ui) => ui.authToken)
export const cardNameSelector = createSelector(selectUI, (ui) => ui.userCard.name)
export const cardNumberSelector = createSelector(selectUI, (ui) => ui.userCard.cardNumber)
export const cardDateSelector = createSelector(selectUI, (ui) => ui.userCard.cardDate)
export const cardCvcSelector = createSelector(selectUI, (ui) => ui.userCard.cvc)
export const currentCardNameSelector = createSelector(selectUI, (ui) => ui.currentCard.name)
export const currentCardNumberSelector = createSelector(selectUI, (ui) => ui.currentCard.cardNumber)
export const currentCardDateSelector = createSelector(selectUI, (ui) => ui.currentCard.cardDate)
export const currentCardCvcSelector = createSelector(selectUI, (ui) => ui.currentCard.cvc)
export const cardNumberCounterSelector = createSelector(selectUI, (ui) => ui.currentCard.numberCounter)
export const cardDateCounterSelector = createSelector(selectUI, (ui) => ui.currentCard.dateCounter)
export const addressesSelector = createSelector(selectUI, (ui) => ui.addresses)
export const firstAddressSelector = createSelector(selectUI, (ui) => ui.firstAddress)
export const secondAddressSelector = createSelector(selectUI, (ui) => ui.secondAddress)
export const firstArrayAddressSelector = createSelector(selectUI, (ui) => ui.firstArrayAddress)
export const secondArrayAddressSelector = createSelector(selectUI, (ui) => ui.secondArrayAddress)
export const taxiSelector = createSelector(selectUI, (ui) => ui.needTaxi)
export const coords = createSelector(selectUI, (ui) => ui.coordinates)
export const taxiReadySelector = createSelector(selectUI, (ui) => ui.taxiReady)
export const isCardCompletedSelector = createSelector(selectUI, (ui) => ui.isCardCompleted)
export const cardChangedSelector = createSelector(selectUI, (ui) => ui.cardChanged)
export const activeCarSelector = createSelector(selectUI, (ui) => ui.activeCar)